a = int(input('Введите значение первой переменной типа int '))
b = int(input('Введите значение второй переменной типа int '))
print(a+b)
print(a-b)
print(a*b)
print(a//b)
a = float(input('Введите значение первой переменной типа float '))
b = float(input('Введите значение второй переменной типа float '))
print(a+b)
print(a-b)
print(a*b)
print(a//b)
a = float(input('Введите значение первой переменной типа float '))
b = int(input('Введите значение второй переменной типа int '))
print(a+b)
print(a-b)
print(a*b)
print(a//b)
a = int(input('Введите значение первой переменной типа int '))
b = float(input('Введите значение второй переменной типа float '))
print(a+b)
print(a-b)
print(a*b)
print(a//b)